import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'en' | 'am';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'header.title': 'GIBI-GUBAE',
    'header.placeholder': 'Ask us anything',
    'header.go': 'GO',
    'header.staffSignIn': 'Staff Sign In',
    'header.notifications': 'Notifications',
    // Tabs
    'tab.all': 'All',
    'tab.faith': 'Faith',
    'tab.bible': 'Bible',
    'tab.prayer': 'Prayer',
    'tab.relationships': 'Relationships',
    'tab.struggles': 'Struggles',
    'tab.general': 'General',
    // Notification Modal
    'notification.title': 'Notifications',
    'notification.markAllRead': 'Mark all as read',
    'notification.empty': 'No notifications yet',
    'notification.guestNotice': "Sign in to track which announcements you've read.",
    'notification.viewAll': 'View all notifications',
    // Question Card
    'question.more': 'MORE',
    'question.less': 'LESS',
    'question.answer': 'Answer',
    'question.hideAnswer': 'Hide Answer',
    'question.reply': 'Reply',
    'question.status.answered': 'Answered',
    'question.status.approved': 'Approved',
    'question.status.rejected': 'Rejected',
    'question.status.pending': 'Pending',
    // Sidebar
    'sidebar.noImage': 'No Image Available',
    'sidebar.more': 'MORE',
    'sidebar.less': 'LESS',
    // Hot Questions
    'hotquestions.title': 'Recent Questions',
    'hotquestions.loading': 'Loading...',
    'hotquestions.empty': 'No questions found.',
    'hotquestions.general': 'General',
    // Success Modal
    'success.title': 'Question Received!',
    'success.body': 'Thank you for reaching out. We will post your question along with the answer as soon as it is ready.',
    'success.button': 'Got it, thanks!',
    // Sign In Modal
    'signin.title': 'GIBI-GUBAE',
    'signin.subtitle': 'Ask your questions anonymously',
    'signin.email': 'Email',
    'signin.email.placeholder': 'Enter your email',
    'signin.password': 'Password',
    'signin.password.placeholder': 'Enter your password',
    'signin.submit': 'Sign In',
    'signin.joinNow': 'Join now',
    'signin.register': 'Register',
    'signin.needAccount': 'Need an account?',
    'signin.haveAccount': 'Already have an account?',
    'signin.guestContinue': 'Continue as Guest',
    'signin.pendingApproval': 'New staff pending approval',
    'signin.notApproved': 'Your account is pending admin approval.',
    'signin.invalidCredentials': 'Invalid credentials',
    'signin.failedRegister': 'Failed to register',
    'signin.notice.privacyTitle': 'Your Privacy Matters',
    'signin.notice.privacyBody': 'All questions and interactions are completely confidential and anonymous.',
    'signin.notice.approvalTitle': 'Admin Approval Required',
    'signin.notice.approvalBody': 'New staff login requires admin approval. You will be notified once your account is approved.',
    'signin.requestAccess': 'Request Access',
    // Auth Page
    'auth.backToHome': 'Back to Home',
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create an Account',
    'auth.loginDesc': 'Sign in to ask questions, view responses, or access staff moderation',
    'auth.registerDesc': 'Register for staff moderation or student discussion participation',
    'auth.emailLabel': 'Email Address',
    'auth.emailPlaceholder': 'you@example.com',
    'auth.passwordLabel': 'Password',
    'auth.passwordPlaceholder': '••••••••',
    'auth.pleaseWait': 'Please wait...',
    'auth.signInBtn': 'Sign In',
    'auth.createAccountBtn': 'Create Account',
    'auth.portalNotice': 'Attendees and students can join rooms and ask questions anonymously without an account. Staff members require administrative approval before accessing moderation tools.',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.registerHere': 'Register here',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signInHere': 'Sign in here',
    'auth.pendingApprovalNotice': 'Your staff account is pending admin approval. You will be able to log in once approved.',
    'auth.invalidLogin': 'Invalid email or password',
    'auth.failedRegister': 'Failed to register',
    'auth.registrationSuccessful': 'Registration successful! New staff accounts are pending admin approval.',
    'auth.emailRequired': 'Email is required',
    'auth.emailInvalid': 'Email must be a valid email',
    'auth.passwordRequired': 'Password is required',
    'auth.passwordLength': 'Password length must be at least 6 characters long',
    // Staff Page
    'staff.signOut': 'Sign Out',
    'staff.questions': 'Questions',
    'staff.rooms': 'Rooms',
    'staff.staff': 'Staff',
    'staff.history': 'History',
    'staff.filter.all': 'All',
    'staff.filter.pending': 'Pending',
    'staff.filter.approved': 'Approved',
    'staff.filter.answered': 'Answered',
    'staff.filter.rejected': 'Rejected',
    'staff.badge.approved': 'Approved (Public)',
    'staff.badge.answered': 'Answered (Public)',
    'staff.badge.rejected': 'Rejected (Hidden)',
    'staff.badge.pending': 'Pending Moderation',
    'staff.dash.title': 'Staff Moderation Dashboard',
    'staff.dash.desc': 'Decide question visibility and write answers. Questions with',
    'staff.dash.descApproved': 'APPROVED',
    'staff.dash.descOr': 'or',
    'staff.dash.descAnswered': 'ANSWERED',
    'staff.dash.descVisible': 'are visible to the public.',
    'staff.refresh': 'Refresh',
    'staff.room': 'ROOM',
    'staff.superadmin': 'SUPER ADMIN',
    'staff.noQuestions': 'No questions found',
    'staff.noQuestionsStatus': 'There are no questions with status',
    'staff.setStatus': 'Set Question Status:',
    'staff.setCategory': 'Set Category:',
    'staff.existingReplies': 'Existing Replies',
    'staff.writeResponse': 'Write response (submitting automatically marks status as',
    'staff.placeholder': 'Type your official answer here...',
    'staff.submitAnswer': 'Submit Answer',
    'staff.rooms.title': 'Staff Discussion Rooms',
    'staff.rooms.desc': 'Manage active rooms and view their 6-digit access keys. Share keys with attendees to let them join without logging in.',
    'staff.createRoom': 'CREATE ROOM',
    'staff.noRooms': 'No rooms created yet',
    'staff.noRoomsDesc': 'Create a room to start group discussions. A unique 6-digit access key will be generated automatically.',
    'staff.roomKey': 'Room Key',
    'staff.copied': 'Copied!',
    'staff.copyKey': 'Copy Key',
    'staff.enterRoom': 'Enter Room',
    'staff.staff.title': 'Chaplain & Staff Community',
    'staff.staff.desc': 'Welcome to the staff team. Your responsibility is to oversee discussions, approve student questions for public visibility, provide sound theological answers, and maintain fruitful fellowship.',
    'staff.staff.box1Title': 'Approved Questions',
    'staff.staff.box1Desc': 'Visible to everyone without requiring login. Use for edifying questions.',
    'staff.staff.box2Title': 'Room Keys',
    'staff.staff.box2Desc': 'Each room has a unique 6-digit key. Share keys with students so they can join freely.',
    'staff.staff.box3Title': 'Official Answers',
    'staff.staff.box3Desc': 'Submitting an answer automatically updates the status to Answered (Public).',
    'staff.history.title': 'Answered & Moderated Archive',
    'staff.history.archived': 'Archived',
    'staff.history.reply': 'Reply:',
    'staff.modal.createTitle': 'Create Discussion Room',
    'staff.modal.roomName': 'Room Name',
    'staff.modal.namePlaceholder': 'e.g., Weekly Bible Study',
    'staff.modal.category': 'Category',
    'staff.modal.description': 'Description',
    'staff.modal.descPlaceholder': 'What will this room focus on?',
    'staff.modal.keyNotice': 'A random 6-digit Room Key will be generated automatically for attendees.',
    'staff.modal.createBtn': 'Create Room',
    'staff.modal.successTitle': 'Room Created Successfully!',
    'staff.modal.shareableKey': 'Shareable 6-Digit Room Key',
    'staff.modal.joinNotice': 'Attendees and students can join this room without logging in using this 6-digit key.',
    'staff.modal.done': 'Done',
    'staff.cat.faith': 'Faith',
    'staff.cat.bible': 'Bible',
    'staff.cat.prayer': 'Prayer',
    'staff.cat.relationships': 'Relationships',
    'staff.cat.struggles': 'Struggles',
    'staff.cat.general': 'General',
    'staff.status.active': 'ACTIVE',
    'staff.status.inactive': 'INACTIVE',
    'staff.status.created': 'Created',
  },
  am: {
    // Header
    'header.title': 'ግቢ-ጉባኤ',
    'header.placeholder': 'ጥያቄዎን ይጠይቁ',
    'header.go': 'ላክ',
    'header.staffSignIn': 'የሰራተኛ መግቢያ',
    'header.notifications': 'ማሳወቂያዎች',
    // Tabs
    'tab.all': 'ሁሉም',
    'tab.faith': 'እምነት',
    'tab.bible': 'መጽሐፍ ቅዱስ',
    'tab.prayer': 'ጸሎት',
    'tab.relationships': 'ግንኙነቶች',
    'tab.struggles': 'ፈተናዎች',
    'tab.general': 'ጠቅላላ',
    // Notification Modal
    'notification.title': 'ማሳወቂያዎች',
    'notification.markAllRead': 'ሁሉንም እንደተነበበ ምልክት አድርግ',
    'notification.empty': 'ምንም ማሳወቂያ የለም',
    'notification.guestNotice': 'ያነበቧቸውን ማሳወቂያዎች ለመከታተል ይግቡ።',
    'notification.viewAll': 'ሁሉንም ማሳወቂያዎች ይመልከቱ',
    // Question Card
    'question.more': 'ተጨማሪ',
    'question.less': 'አሳጥር',
    'question.answer': 'መልስ',
    'question.hideAnswer': 'መልስ ደብቅ',
    'question.reply': 'ምላሽ',
    'question.status.answered': 'ተመልሷል',
    'question.status.approved': 'ጸድቋል',
    'question.status.rejected': 'ተቀባይነት አላገኘም',
    'question.status.pending': 'በመጠባበቅ ላይ',
    // Sidebar
    'sidebar.noImage': 'ምስል የለም',
    'sidebar.more': 'ተጨማሪ',
    'sidebar.less': 'አሳጥር',
    // Hot Questions
    'hotquestions.title': 'የቅርብ ጊዜ ጥያቄዎች',
    'hotquestions.loading': 'በመጫን ላይ...',
    'hotquestions.empty': 'ምንም ጥያቄ አልተገኘም።',
    'hotquestions.general': 'ጠቅላላ',
    // Success Modal
    'success.title': 'ጥያቄዎ ደርሷል!',
    'success.body': 'ጥያቄዎን ስለ አቀረቡ እናመሰግናለን። ጥያቄዎን ከመልሱ ጋር እንደተዘጋጀ እናስቀምጣለን።',
    'success.button': 'እሺ',
    // Sign In Modal
    'signin.title': 'ግቢ-ጉባኤ',
    'signin.subtitle': 'ጥያቄዎን ሳይታወቁ ይጠይቁ',
    'signin.email': 'ኢሜይል',
    'signin.email.placeholder': 'ኢሜይልዎን ያስገቡ',
    'signin.password': 'የይለፍ ቃል',
    'signin.password.placeholder': 'የይለፍ ቃልዎን ያስገቡ',
    'signin.submit': 'ግባ',
    'signin.joinNow': 'አሁን ተቀላቀሉ',
    'signin.register': 'ይመዝገቡ',
    'signin.needAccount': 'መለያ የለዎትም?',
    'signin.haveAccount': 'መለያ አለዎት?',
    'signin.guestContinue': 'እንደ እንግዳ ቀጥል',
    'signin.pendingApproval': 'ፍቃድ ያስፈልጋል ይጠበቁ ',
    'signin.notApproved': 'መለያዎ የአስተዳዳሪ ፍቃድ እየጠበቀ ነው።',
    'signin.invalidCredentials': 'ኢሜይሉ ወይም የይለፍ ቃሉ ትክክል አይደለም',
    'signin.failedRegister': 'ምዝገባ አልተሳካም',
    'signin.notice.privacyTitle': 'ምስጢርዎ ይጠበቃል',
    'signin.notice.privacyBody': 'ሁሉም ጥያቄዎች እና ግንኙነቶች ሚስጥራዊ እና ስም-አልባ ናቸው።',
    'signin.notice.approvalTitle': 'የአስተዳዳሪ ፍቃድ ያስፈልጋል',
    'signin.notice.approvalBody': 'አዲስ የሰራተኛ መግቢያ የአስተዳዳሪ ፍቃድ ያስፈልጋል። መለያዎ ሲፈቀድ ይነገርዎታል።',
    'signin.requestAccess': 'መዳረሻ ይጠይቁ',
    // Auth Page
    'auth.backToHome': 'ወደ ዋና ገጽ ተመለስ',
    'auth.welcomeBack': 'እንኳን ደህና መጡ',
    'auth.createAccount': 'መለያ ይፍጠሩ',
    'auth.loginDesc': 'ጥያቄዎችን ለመጠየቅ፣ ምላሾችን ለማየት ወይም የሰራተኛ አስተዳደርን ለመጠቀም ይግቡ',
    'auth.registerDesc': 'ለሰራተኛ አስተዳደር ወይም ለተማሪዎች የውይይት ተሳትፎ ይመዝገቡ',
    'auth.emailLabel': 'የኢሜይል አድራሻ',
    'auth.emailPlaceholder': 'you@example.com',
    'auth.passwordLabel': 'የይለፍ ቃል',
    'auth.passwordPlaceholder': '••••••••',
    'auth.pleaseWait': 'እባክዎ ይጠብቁ...',
    'auth.signInBtn': 'ግባ',
    'auth.createAccountBtn': 'መለያ ይፍጠሩ',
    'auth.portalNotice': 'ተሰብሳቢዎች እና ተማሪዎች ያለ መለያ ወደ ክፍሎች መቀላቀል እና በጥብቅ ምስጢራዊነት ጥያቄዎችን መጠየቅ ይችላሉ። የሰራተኛ አባላት የማስተዳደሪያ መሳሪያዎችን ከመጠቀማቸው በፊት የአስተዳዳሪ ፍቃድ ያስፈልጋቸዋል።',
    'auth.dontHaveAccount': 'መለያ የለዎትም?',
    'auth.registerHere': 'እዚህ ይመዝገቡ',
    'auth.alreadyHaveAccount': 'አካውንት አልዎት?',
    'auth.signInHere': 'እዚህ ይግቡ',
    'auth.pendingApprovalNotice': 'የሰራተኛ መለያዎ የአስተዳዳሪ ፍቃድ እየጠበቀ ነው። ሲፈቀድ መግባት ይችላሉ።',
    'auth.invalidLogin': 'የኢሜይል አድራሻ ወይም የይለፍ ቃል ትክክል አይደለም',
    'auth.failedRegister': 'ምዝገባ አልተሳካም',
    'auth.registrationSuccessful': 'ምዝገባው ተሳክቷል! አዲስ የሰራተኛ መለያዎች የአስተዳዳሪ ፍቃድ እየጠበቁ ናቸው።',
    'auth.emailRequired': 'ኢሜይል ያስፈልጋል',
    'auth.emailInvalid': 'ኢሜይል ትክክለኛ መሆን አለበት',
    'auth.passwordRequired': 'የይለፍ ቃል ያስፈልጋል',
    'auth.passwordLength': 'የይለፍ ቃል ርዝመት ቢያንስ 6 ፊደላት መሆን አለበት',
    // Staff Page
    'staff.signOut': 'ውጣ',
    'staff.questions': 'ጥያቄዎች',
    'staff.rooms': 'ክፍሎች',
    'staff.staff': 'ሰራተኞች',
    'staff.history': 'ታሪክ',
    'staff.filter.all': 'ሁሉም',
    'staff.filter.pending': 'በመጠባበቅ ላይ',
    'staff.filter.approved': 'የጸደቁ',
    'staff.filter.answered': 'የተመለሱ',
    'staff.filter.rejected': 'ውድቅ የተደረጉ',
    'staff.badge.approved': 'የጸደቀ (ለህዝብ)',
    'staff.badge.answered': 'የተመለሰ (ለህዝብ)',
    'staff.badge.rejected': 'ውድቅ የተደረገ (የተደበቀ)',
    'staff.badge.pending': 'ፍቃድ በመጠባበቅ ላይ',
    'staff.dash.title': 'የሰራተኞች ማስተዳደሪያ',
    'staff.dash.desc': 'የጥያቄዎችን እይታ ይወስኑ እና መልስ ይፃፉ።',
    'staff.dash.descApproved': 'የጸደቀ',
    'staff.dash.descOr': 'ወይም',
    'staff.dash.descAnswered': 'የተመለሰ',
    'staff.dash.descVisible': 'ሁኔታ ያላቸው ለህዝብ ይታያሉ።',
    'staff.refresh': 'አድስ',
    'staff.room': 'ክፍል',
    'staff.superadmin': 'ዋና አስተዳዳሪ',
    'staff.noQuestions': 'ምንም ጥያቄ አልተገኘም',
    'staff.noQuestionsStatus': 'በዚህ ሁኔታ ውስጥ ያሉ ጥያቄዎች የሉም',
    'staff.setStatus': 'የጥያቄ ሁኔታን ይወስኑ:',
    'staff.setCategory': 'ምድብ ይምረጡ:',
    'staff.existingReplies': 'ነባር ምላሾች',
    'staff.writeResponse': 'መልስ ይፃፉ (መልስ ከላኩ በኋላ ሁኔታው በራሱ ወደ መልስ የተመለሰ ይለወጣል)',
    'staff.placeholder': 'ኦፊሻል መልስዎን እዚህ ይፃፉ...',
    'staff.submitAnswer': 'መልስ አስገባ',
    'staff.rooms.title': 'የሰራተኞች የውይይት ክፍሎች',
    'staff.rooms.desc': 'ክፍሎችን ያስተዳድሩ እና ባለ 6 አሃዝ ቁልፍዎን ይመልከቱ። ተሰብሳቢዎች ሳይገቡ እንዲቀላቀሉ ቁልፎችን ያጋሩ።',
    'staff.createRoom': 'ክፍል ፍጠር',
    'staff.noRooms': 'ምንም ክፍል አልተፈጠረም',
    'staff.noRoomsDesc': 'የውይይት ክፍል ለመጀመር ይፍጠሩ። ልዩ የሆነ 6 አሃዝ ቁልፍ በራሱ ይፈጠራል',
    'staff.roomKey': 'የክፍል ቁልፍ',
    'staff.copied': 'ተቀድቷል!',
    'staff.copyKey': 'ቁልፍ ቅዳ',
    'staff.enterRoom': 'ወደ ክፍል ይግቡ',
    'staff.staff.title': 'የአገልጋዮች እና የሰራተኞች ማህበረሰብ',
    'staff.staff.desc': 'ወደ የሰራተኞች ቡድን እንኳን ደህና መጡ። የእርስዎ ኃላፊነት ውይይቶችን መቆጣጠር፣ የተማሪዎችን ጥያቄዎች ለህዝብ እንዲታዩ ማጽደቅ፣ ትክክለኛ መጽሐፍ ቅዱሳዊ መልሶችን መስጠት እና ፍሬያማ ህብረትን መጠበቅ ነው።',
    'staff.staff.box1Title': 'የጸደቁ ጥያቄዎች',
    'staff.staff.box1Desc': 'መግባት ሳያስፈልግ ለሁሉም ይታያሉ። ለሚያንጹ ጥያቄዎች ይጠቀሙበት።',
    'staff.staff.box2Title': 'የክፍል ቁልፎች',
    'staff.staff.box2Desc': 'እያንዳንዱ ክፍል ባለ 6 አሃዝ ቁልፍ አለው። ተሰብሳቢዎች በቀላሉ እንዲቀላቀሉ ቁልፉን ያጋሩ።',
    'staff.staff.box3Title': 'ኦፊሻል መልሶች',
    'staff.staff.box3Desc': 'መልስ ሲያቀርቡ ሁኔታው በራሱ ወደ መልስ ተመለሰ በሚል ይስተካከላል።',
    'staff.history.title': 'መልስ የተሰጣቸው እና የተስተካከሉ ጥያቄዎች',
    'staff.history.archived': 'በማህደር ተቀምጠዋል',
    'staff.history.reply': 'መልስ:',
    'staff.modal.createTitle': 'የውይይት ክፍል ይፍጠሩ',
    'staff.modal.roomName': 'የክፍሉ ስም',
    'staff.modal.namePlaceholder': 'ለምሳሌ፡ ሳምንታዊ የመጽሐፍ ቅዱስ ጥናት',
    'staff.modal.category': 'ምድብ',
    'staff.modal.description': 'መግለጫ',
    'staff.modal.descPlaceholder': 'የክፍሉ ትኩረት ምንድነው?',
    'staff.modal.keyNotice': 'ባለ 6 አሃዝ የክፍል ቁልፍ በራሱ ለተሰብሳቢዎች ይፈጠራል።',
    'staff.modal.createBtn': 'ክፍል ፍጠር',
    'staff.modal.successTitle': 'ክፍሉ በተሳካ ሁኔታ ተፈጥሯል!',
    'staff.modal.shareableKey': 'ለማጋራት ባለ 6 አሃዝ የክፍል ቁልፍ',
    'staff.modal.joinNotice': 'ተሰብሳቢዎች እና ተማሪዎች ይሄንን ቁልፍ በመጠቀም ሳይገቡ ክፍል መቀላቀል ይችላሉ።',
    'staff.modal.done': 'ጨርስ',
    'staff.cat.faith': 'እምነት',
    'staff.cat.bible': 'መጽሐፍ ቅዱስ',
    'staff.cat.prayer': 'ጸሎት',
    'staff.cat.relationships': 'ግንኙነት',
    'staff.cat.struggles': 'ትግሎች',
    'staff.cat.general': 'ጠቅላላ',
    'staff.status.active': 'እንቅስቃሴ ላይ',
    'staff.status.inactive': 'እንቅስቃሴ-አልባ',
    'staff.status.created': 'የተፈጠረው',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('app-language');
    return (stored === 'am' || stored === 'en') ? stored : 'en';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'am' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key] ?? translations['en'][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
